In [1]:
import numpy as np

In [2]:
scalar = 2.50
vector = np.array ([2,8,5])   # Original ([2,8,5,4])
matrix = np.array ([
    [9,7],
    [4,1],
    [8,2],
])

In [3]:
tensor = np.array ([
    
[[225, 225, 225], [225, 225, 225], [225, 225, 225]],
[[0, 0, 0],       [0, 0, 0],       [0, 0, 0]],
[[112, 112, 112], [112, 112, 112], [112, 112, 112]]

])

In [4]:
print(matrix)

[[9 7]
 [4 1]
 [8 2]]


In [5]:
matrix_t = matrix.T
print(matrix_t)

[[9 4 8]
 [7 1 2]]


In [ ]:
# Matrix(3,2) + Vector(1,3) ❌
# Example 1 ⚡

A = vector + matrix

In [7]:
# The Transpose of a Matrix + Vector ✔
# Example 2 ⚡

B = matrix_t + vector
print(B)

[[11 12 13]
 [ 9  9  7]]


In [10]:
# Matrix_t + Scalar
# Example 3 ⚡

C = matrix_t + scalar
print(C)

[[11.5  6.5 10.5]
 [ 9.5  3.5  4.5]]


In [9]:
print(matrix_t)

[[9 4 8]
 [7 1 2]]


In [13]:
# Matrix_t + new upper vector. Python will broadcast the lower oner
# Example 4 ⚡

D = matrix_t + np.array([2.5,2.5,2.5]) #this is a new vector
print(D)

[[11.5  6.5 10.5]
 [ 9.5  3.5  4.5]]


In [14]:
# Challenge / Homework

In [18]:
vector_c = np.array([1000,0,1000,0,1000])
matrix_c = np.array([
    [ 1, 2, 3, 4, 5],
    [11,12,13,14,15],
    [21,22,23,24,25],
    [31,32,33,34,35],
    [41,42,43,44,45]
])

In [21]:
sum_c = vector_c + matrix_c
print(sum_c)

[[1001    2 1003    4 1005]
 [1011   12 1013   14 1015]
 [1021   22 1023   24 1025]
 [1031   32 1033   34 1035]
 [1041   42 1043   44 1045]]


In [22]:
sum_d = matrix_c + vector_c 
print(sum_d)

[[1001    2 1003    4 1005]
 [1011   12 1013   14 1015]
 [1021   22 1023   24 1025]
 [1031   32 1033   34 1035]
 [1041   42 1043   44 1045]]
