In [1]:
import numpy as np

In [3]:
A = np.array([[2,3],[5,7],[11,13]])
B = np.array([[1,3],[2,1]])
C = np.array([[3,1],[4,2]])
print(A, "\n")
print(B, "\n")
print(C)

[[ 2  3]
 [ 5  7]
 [11 13]] 

[[1 3]
 [2 1]] 

[[3 1]
 [4 2]]
