In [1]:
import numpy as np

In [2]:
A = np.array([[1,2],[4,5],[7,8]])
B = np.array([[2,3],[5,7]])

print(A, "\n")
print(B)

[[1 2]
 [4 5]
 [7 8]] 

[[2 3]
 [5 7]]


In [3]:
Z = A.dot(B).T 
J = B.T.dot(A.T)
print(Z)
print(J)

[[12 33 54]
 [17 47 77]]
[[12 33 54]
 [17 47 77]]


In [4]:
#    ⚡ Quick property ⚡
#    (A * B)^t   =  B^t * A^t

X = A.dot(B).T == B.T.dot(A.T)
print(X)

[[ True  True  True]
 [ True  True  True]]
