In [1]:
# Ax=b
# Now to solve x 
# I multiply the inverse of A for both sides of the equation. 

# Staying as follows: 
#   --> A * x = b

#   --> inv_A * A * x = inv_A * b   #Side note inv_A * A equals Inverse=I🔴

#   --> I * x = inv_A * b 

#   --> x = inv_A * b

# 'I' means Inverse 🔴



"""
x = A.dot(inverse_of_A) 
A * A^-1🔴 with inner product
print(x) 

#Returns the Identity💧"""

'\nx = A.dot(inverse_of_A) \nA * A^-1🔴 with inner product\nprint(x) \n\n#Returns the Identity💧'

In [2]:
import numpy as np

In [3]:
np.set_printoptions(suppress=True)

In [4]:
# System of linear equations 🎭
"""
Ax = b

3x + y = 1
2x + y = 1

[3 1]  [x] = [1]
[2 1]  [y] = [1]
  A     x     b


"""

'\n3x + y = 1\n2x + y = 1\n\n[3 1]  [x] = [1]\n[2 1]  [y] = [1]\n  A     x     b\n\nAx = b\n'

In [5]:
#New matrix A
A = np.array([[3,1],[2,1]])
print(A)

[[3 1]
 [2 1]]


In [10]:
#Inverse of A🔴 = A^-1
inv_A = np.linalg.inv(A)
print(inv_A) #in Floats

[[ 1. -1.]
 [-2.  3.]]


In [6]:
b = np.array([[1],[1]])
print(b)

[[1]
 [1]]


In [8]:
x = inv_A.dot(b)
print(x)

[[0.]
 [1.]]


In [9]:
# 2nd example ------------- 🎭
"""
Ax = b

3x + y = 3
2x + y = 7

[3 1]  [x] = [3]
[2 1]  [y] = [7]
  A     x     b

"""

In [11]:
ex_2 = inv_A.dot([[3],[7]])
print(ex_2)

[[-4.]
 [15.]]


In [12]:
#Now backwards  ---> A normal Matrix * ex_2    ex_2 = inv_A.dot([[3],[7]])

ex_2_back = A.dot(ex_2)
print(ex_2_back)
 

[[3.]
 [7.]]
