In [1]:
import numpy as np

In [2]:
scalar = 7.45

In [3]:
vector = np.array ([2,8,5,4])

In [4]:
matrix = np.array ([[9,3,7],[4,6,1]])


In [5]:
tensor = np.array ([
    
[[ 225, 225, 225], [ 225, 225, 225], [ 225, 225, 225]],
[[0, 0, 0], [0, 0, 0], [0, 0, 0]],
[[112, 112, 112], [112, 112, 112], [112, 112, 112]]

])

In [6]:
# Vector
print(vector)
print("\n")
print(vector.shape)
print("\n")
print(len(vector))

[2 8 5 4]


(4,)


4


In [7]:
# Matrix
print(matrix)
print("\n")
print(matrix.shape)
print("\n")
print(len(matrix))

[[9 3 7]
 [4 6 1]]


(2, 3)


2


In [8]:
# Tensor

print(tensor)
print("\n")
print(tensor.shape)
print("\n")
print(len(tensor))

[[[225 225 225]
  [225 225 225]
  [225 225 225]]

 [[  0   0   0]
  [  0   0   0]
  [  0   0   0]]

 [[112 112 112]
  [112 112 112]
  [112 112 112]]]


(3, 3, 3)


3
