In [1]:
import numpy as np

In [2]:
scalar = 2.50
vector = np.array ([8,1])   # Original ([2,8,5,4])
matrix = np.array ([
    [9,7],
    [4,1],
    [8,2],
])

In [3]:
broadcasting = matrix * vector #broadcasting method
print(broadcasting)

[[72  7]
 [32  1]
 [64  2]]


In [6]:
#Dot product or Inner product

Dot = matrix.dot(vector) #NOT Broadcasting
print(Dot)

Dot_2 = np.dot(matrix, vector)
print(Dot_2)

[79 33 66]
[79 33 66]


In [5]:
# ⚡ Outer Product ⚡

x = [[1,2],[3,4]] #matrix
y = [[10,20],[30,40]] #2nd matrix

C = np.outer(x, y) #both matrices as parameters
print(C)

# First row --->   1x10 then 1x20 then 1x30 an so on
# Same with 2, 3, and 4:   3x10=30, 3x20=60, 3x30=90, 3x40=120

[[ 10  20  30  40]
 [ 20  40  60  80]
 [ 30  60  90 120]
 [ 40  80 120 160]]


In [13]:
#Homework

matrix_c = np.array([
    [[2,1],
     [4,9]],
    
    [[5,6],
     [3,8]],
])
vector_c = np.array([10,100])

both = matrix_c * vector_c
print(both)

[[[ 20 100]
  [ 40 900]]

 [[ 50 600]
  [ 30 800]]]


In [18]:
#c = Challenge  /  Homework ⚡

vector_c = np.array([10,100]) #New vector
matrix_c = np.array([
    [[2,1],
     [4,9]],
    
    [[5,6],
     [3,8]],
])                             #New matrix

m = matrix_c.dot(vector_c) #Inner product
v = vector.dot(matrix_c)   #Inner product

print(m)
print("\n") # new line
print(v)

[[120 940]
 [650 830]]


[[20 17]
 [43 56]]
