In [1]:
import numpy as np

In [11]:
A = np.array([[2,3],[5,7],[11,13]])
B = np.array([[1,3],[2,1]])
C = np.array([[3,1],[4,2]])
print(A, "\n")
print(B, "\n")
print(C)

[[ 2  3]
 [ 5  7]
 [11 13]] 

[[1 3]
 [2 1]] 

[[3 1]
 [4 2]]


In [12]:
#🟢 Associative   ✔    A*(B*C) = (A*B)*C
E = A.dot(B.dot(C))
F = (A.dot(B)).dot(C)

print(E, "\n")
print(F)

[[ 60  26]
 [145  63]
 [295 129]] 

[[ 60  26]
 [145  63]
 [295 129]]


In [9]:
#🟢 Distributive  ✔   A*(B+C) = (A*B)+(A*C)
G = A.dot(B+C)
H = (A.dot(B) + A.dot(C))

print(G)
print(H)
print("\n", G==H)

[[ 26  17]
 [ 62  41]
 [122  83]]
[[ 26  17]
 [ 62  41]
 [122  83]]

 [[ True  True]
 [ True  True]
 [ True  True]]


In [8]:
#🟢 Commutative ❌ B*C  =  C*B
I = B.dot(C)
J = C.dot(B)

print(I)
print(J)
print("\n", I==J)

[[15  7]
 [10  4]]
[[ 5 10]
 [ 8 14]]

 [[False False]
 [False False]]


In [6]:
v1 = np.array([2,8,1])
v2 = np.array([3,9,4])

v1_t = v1.T
v2_t = v2.T

print(v1)
print(v2)
print("\n")
print(v1_t) #but vertical
print(v2_t) #but vertical

[2 8 1]
[3 9 4]


[2 8 1]
[3 9 4]


In [14]:
v1_t_dot_v2 = v1.T.dot(v2)

v2_t_dot_v1 = v2.T.dot(v1)

print(v1_t_dot_v2)

print(v2_t_dot_v1)

82
82


In [26]:
# ⭐ Challege ⭐

m1 = np.array([[9,5],[8,6],[10,4],[2,1]])
m2 = np.array([[9,5,9],[8,6,12],])

print(m1, m1.shape, "\n") # new line
print(m2, m2.shape, "\n") # new line

new_m_1 = m1.dot(m2)
print(new_m_1) 

"""new_m_2 = m2.dot(m1)
   #This doesn't work.
   #Because the rows(4) != from the columns(3)"""


[[ 9  5]
 [ 8  6]
 [10  4]
 [ 2  1]] (4, 2) 

[[ 9  5  9]
 [ 8  6 12]] (2, 3) 

[[121  75 141]
 [120  76 144]
 [122  74 138]
 [ 26  16  30]]
