In [1]:
import numpy as np

In [2]:
# 💧 IDENTITY 💧

In [3]:
identity_m = np.eye(3) #It returns floats💧
print(identity_m)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [4]:
vector = np.array([[3],[5],[7]])
print(vector)

[[3]
 [5]
 [7]]


In [5]:
print(identity_m.dot(vector)) #Same vector but returned in Floats
#identity💧 * vector

[[3.]
 [5.]
 [7.]]


In [6]:
# The Identity matrix is neutral! 💧

In [7]:
# 🩹 Careful! Linear transformations. 🩹
# These DO change the matrix
"""
[2,3][1]=5
[4,5][1]=9
"""
# We're modifying the space

'\n[2,3][1]=5\n[4,5][1]=9\n'

In [8]:
# 🔴 INVERSE 🔴

In [9]:
"""The inverse of 5x3 = 15 
    is 15/3 = 5""" 

'The inverse of 5x3 = 15 \n    is 15/3 = 5'

In [10]:
# A = Matrix, ok?
""" 
A * something = Identity💧 ?

Let's see how 👇

A * A^-1 = Identity """

" \nA * something = Identity💧 ?\n\nLet's see how 👇\n\nA * A^-1 = Identity "

In [11]:
A = np.array([[1,0,1],[0,1,1],[-1,1,1]])

print(A)

[[ 1  0  1]
 [ 0  1  1]
 [-1  1  1]]


In [12]:
inverse_of_A = np.linalg.inv(A) #Numpy operation

print(inverse_of_A)

[[ 0.  1. -1.]
 [-1.  2. -1.]
 [ 1. -1.  1.]]


In [13]:
# 🔴 A^-1 = Inverse

In [21]:
x = A.dot(inverse_of_A) #A * A^-1🔴 with inner product
print(x) 
#Returns the Identity💧

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [15]:
#This 👆 is not always the case
# When there's no inverse🔴 we call it = Singular Matrix🟢

In [16]:
sing = np.array([[1,1],[1,1]]) #Singular🟢
print(sing)

[[1 1]
 [1 1]]


In [20]:
Z = np.linalg.inv(sing)
print(Z)
#The inverse of a Sing🟢 doesn't exist. It throws error

LinAlgError: Singular matrix

In [19]:
"""
A*x = b

x = A^-1*b
"""
# ex = np.linalg.inv(A).dot(b)
# print(ex)

NameError: name 'b' is not defined

In [ ]:
# ⭐ if the determinant of a matrix is
# "0" it is a Singular matrix, 
# that is, a matrix that has no inverse